<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML20178" name="io.mosip.authentication.tests.OtpGeneration" tests="38" failures="0" timestamp="28 Jun 2019 13:36:44 GMT" time="50.979" errors="4">
  <testcase name="Authentication_OTPGenerate_With_Invalid_expired_VID_Neg" time="1.128" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Valid_Request_IntegrationTest_Smoke_Pos" time="12.821" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_without_OTPChannel_IntegrationTest_Neg" time="0.967" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_individualId_VID_Neg" time="0.843" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Check_OTP_Flooding_Neg" time="2.610" classname="io.mosip.authentication.tests.OtpGeneration">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at otp-generate-response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at otp-generate-response output validation
	at io.mosip.authentication.tests.OtpGeneration.otpGenerationTest(OtpGeneration.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:42)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:30)
]]>
    </error>
  </testcase> <!-- Authentication_OTPGenerate_Check_OTP_Flooding_Neg -->
  <testcase name="Authentication_OTPGenerate_set_email_phone_false_IntegrationTest_Neg" time="0.828" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_phone_otpchannel_Neg" time="0.764" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_transactionID_Neg" time="0.806" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_individualIdType_Neg" time="0.961" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_individualId_VID_as_per_data_definition_Neg" time="0.794" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_null_OTPChannel_IntegrationTest_Neg" time="3.745" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Check_OTP_Flooding_Using_VID_Neg" time="1.999" classname="io.mosip.authentication.tests.OtpGeneration">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at otp-generate-response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at otp-generate-response output validation
	at io.mosip.authentication.tests.OtpGeneration.otpGenerationTest(OtpGeneration.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:42)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:30)
]]>
    </error>
  </testcase> <!-- Authentication_OTPGenerate_Check_OTP_Flooding_Using_VID_Neg -->
  <testcase name="Authentication_OTPGenerate_With_Invalid_deactivated_UIN_Neg" time="0.367" classname="io.mosip.authentication.tests.OtpGeneration">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at otp-generate-response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at otp-generate-response output validation
	at io.mosip.authentication.tests.OtpGeneration.otpGenerationTest(OtpGeneration.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:42)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:30)
]]>
    </error>
  </testcase> <!-- Authentication_OTPGenerate_With_Invalid_deactivated_UIN_Neg -->
  <testcase name="Authentication_OTPGenerate_With_Valid_Request_EMAIL_alone_IntegrationTest_Smoke_Pos" time="2.094" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_requestTime_Neg" time="0.847" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_requestTime_LT30MIN_Neg" time="0.823" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_individualId_VID_Neg" time="0.947" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_Id_Neg" time="0.869" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_Version_Neg" time="0.768" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_transactionID_Neg" time="0.787" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Valid_Request_IntegrationTest_Smoke_Using_VID_Pos" time="0.007" classname="io.mosip.authentication.tests.OtpGeneration">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at HTTP-POST otp-generate-request">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at HTTP-POST otp-generate-request
	at io.mosip.authentication.tests.OtpGeneration.otpGenerationTest(OtpGeneration.java:180)
	at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:42)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:30)
]]>
    </error>
  </testcase> <!-- Authentication_OTPGenerate_With_Valid_Request_IntegrationTest_Smoke_Using_VID_Pos -->
  <testcase name="Authentication_OTPGenerate_With_Invalid_future_requestTime_Neg" time="0.799" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_Id_Neg" time="0.874" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_individualIdType_Neg" time="0.831" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_individualId_UIN_as_per_data_definition_Neg" time="0.798" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_Version_Neg" time="0.936" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_requestTime_GT30MIN_Neg" time="0.766" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Valid_Request_Phone_alone_IntegrationTest_Smoke_Pos" time="1.824" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_individualId_VID_Neg" time="0.861" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_transactionID_Neg" time="0.823" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_Id_Neg" time="1.056" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_requestTime_Neg" time="0.747" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_UIN_Neg" time="0.819" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_individualIdType_Neg" time="0.803" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Null_Version_Neg" time="0.823" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_email_otpchannel_Neg" time="0.781" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_With_Invalid_requestTime_Neg" time="0.799" classname="io.mosip.authentication.tests.OtpGeneration"/>
  <testcase name="Authentication_OTPGenerate_Without_UIN_Neg" time="0.864" classname="io.mosip.authentication.tests.OtpGeneration"/>
</testsuite> <!-- io.mosip.authentication.tests.OtpGeneration -->
