<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="A2MD20092" name="io.mosip.preregistration.tests.ValidateOtp" tests="7" failures="0" timestamp="02 Jul 2019 13:56:07 GMT" time="169.554" errors="1">
  <testcase name="preReg_Authentication_validateWithInvalidUserID" time="27.250" classname="io.mosip.preregistration.tests.ValidateOtp"/>
  <testcase name="preReg_Authentication_validateOtpSendToMobileNo" time="35.203" classname="io.mosip.preregistration.tests.ValidateOtp"/>
  <testcase name="preReg_Authentication_validateOtpSendToEmail" time="32.375" classname="io.mosip.preregistration.tests.ValidateOtp"/>
  <testcase name="validateWithoutGeneratingOtp" time="14.325" classname="io.mosip.preregistration.tests.ValidateOtp">
    <skipped/>
  </testcase> <!-- validateWithoutGeneratingOtp -->
  <testcase name="login" time="36.528" classname="io.mosip.preregistration.tests.ValidateOtp">
    <error type="org.hibernate.HibernateException" message="The internal connection pool has reached its maximum size and no connection is currently available!">
      <![CDATA[org.hibernate.HibernateException: The internal connection pool has reached its maximum size and no connection is currently available!
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.poll(DriverManagerConnectionProviderImpl.java:280)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PoolState.getConnection(DriverManagerConnectionProviderImpl.java:430)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.getConnection(DriverManagerConnectionProviderImpl.java:171)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:254)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:262)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:236)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:86)
	at org.hibernate.internal.AbstractSharedSessionContract.beginTransaction(AbstractSharedSessionContract.java:452)
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:350)
	at com.sun.proxy.$Proxy41.beginTransaction(Unknown Source)
	at io.mosip.preregistration.util.PreRegistartionDataBaseAccess.getDataBaseConnection(PreRegistartionDataBaseAccess.java:36)
	at io.mosip.preregistration.util.PreRegistartionDataBaseAccess.getDbData(PreRegistartionDataBaseAccess.java:43)
	at io.mosip.preregistration.dao.PreregistrationDAO.getOTP(PreregistrationDAO.java:83)
	at io.mosip.util.PreRegistrationLibrary.getToken(PreRegistrationLibrary.java:329)
	at io.mosip.preregistration.tests.ValidateOtp.login(ValidateOtp.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:42)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:30)
]]>
    </error>
  </testcase> <!-- login -->
  <testcase name="preReg_Authentication_validateWithInvalidOtp" time="1.132" classname="io.mosip.preregistration.tests.ValidateOtp"/>
  <testcase name="preReg_Authentication_blockedUser" time="22.741" classname="io.mosip.preregistration.tests.ValidateOtp"/>
</testsuite> <!-- io.mosip.preregistration.tests.ValidateOtp -->
