<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML30049" name="io.mosip.e2e.tests.EndToEndRun" tests="20" failures="0" timestamp="15 Jul 2019 11:10:51 GMT" time="324.512" errors="10">
  <testcase name="E2ERun_PrIdOfChildWithDocs_regProcSyncPacket" time="1.536" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfChildWithoutDocs_regProcSyncPacket" time="1.396" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfAdultWithoutDocs_regProcSyncPacket" time="1.609" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfAdultWithDocs_regProcSyncPacket" time="1.514" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_RegistrationClientPacket_regProcSyncPacket" time="1.404" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfChildWithDocs_regProcUploadPacket" time="1.262" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_RegistrationClientPacket_regProcUploadPacket" time="1.016" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfAdultWithDocs_regProcUploadPacket" time="1.149" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfChildWithoutDocs_regProcUploadPacket" time="0.978" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_PrIdOfAdultWithoutDocs_regProcUploadPacket" time="1.000" classname="io.mosip.e2e.tests.EndToEndRun"/>
  <testcase name="E2ERun_RegistrationClientPacket_regProcValidation" time="61.021" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; {&quot;timestamp&quot;:1563188775309,&quot;status&quot;:404,&quot;error&quot;:&quot;Not Found&quot;,&quot;message&quot;:&quot;No message available&quot;,&quot;path&quot;:&quot;/v1/masterdata/registrationcentershistory/eng/2019-07-15T16:35:22.142Z&quot;}">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> {"timestamp":1563188775309,"status":404,"error":"Not Found","message":"No message available","path":"/v1/masterdata/registrationcentershistory/eng/2019-07-15T16:35:22.142Z"}
at io.mosip.e2e.tests.EndToEndRun.regProcValidation(EndToEndRun.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_RegistrationClientPacket_regProcValidation -->
  <testcase name="E2ERun_PrIdOfChildWithDocs_regProcValidation" time="64.108" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.regProcValidation(EndToEndRun.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfChildWithDocs_regProcValidation -->
  <testcase name="E2ERun_PrIdOfAdultWithDocs_regProcValidation" time="60.864" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.regProcValidation(EndToEndRun.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfAdultWithDocs_regProcValidation -->
  <testcase name="E2ERun_PrIdOfChildWithoutDocs_regProcValidation" time="60.836" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.regProcValidation(EndToEndRun.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfChildWithoutDocs_regProcValidation -->
  <testcase name="E2ERun_PrIdOfAdultWithoutDocs_regProcValidation" time="60.708" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.regProcValidation(EndToEndRun.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfAdultWithoutDocs_regProcValidation -->
  <testcase name="E2ERun_PrIdOfAdultWithDocs_uinGeneration" time="0.870" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.uinGeneration(EndToEndRun.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfAdultWithDocs_uinGeneration -->
  <testcase name="E2ERun_PrIdOfAdultWithoutDocs_uinGeneration" time="0.840" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.uinGeneration(EndToEndRun.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfAdultWithoutDocs_uinGeneration -->
  <testcase name="E2ERun_RegistrationClientPacket_uinGeneration" time="0.767" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; {&quot;timestamp&quot;:1563188775309,&quot;status&quot;:404,&quot;error&quot;:&quot;Not Found&quot;,&quot;message&quot;:&quot;No message available&quot;,&quot;path&quot;:&quot;/v1/masterdata/registrationcentershistory/eng/2019-07-15T16:35:22.142Z&quot;}">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> {"timestamp":1563188775309,"status":404,"error":"Not Found","message":"No message available","path":"/v1/masterdata/registrationcentershistory/eng/2019-07-15T16:35:22.142Z"}
at io.mosip.e2e.tests.EndToEndRun.uinGeneration(EndToEndRun.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_RegistrationClientPacket_uinGeneration -->
  <testcase name="E2ERun_PrIdOfChildWithDocs_uinGeneration" time="0.817" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.uinGeneration(EndToEndRun.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfChildWithDocs_uinGeneration -->
  <testcase name="E2ERun_PrIdOfChildWithoutDocs_uinGeneration" time="0.817" classname="io.mosip.e2e.tests.EndToEndRun">
    <error type="io.mosip.e2e.util.TestRigException" message="Exception In Registration Processor ---&gt; RPR-SYS-012 --&gt; IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --&gt; Unable to send message to to queue">
      <![CDATA[io.mosip.e2e.util.TestRigException: Exception In Registration Processor ---> RPR-SYS-012 --> IO EXCEPTION ; 
nested exception is io.mosip.registration.processor.core.queue.impl.exception.ConnectionUnavailableException: RPR-MQI-001 --> Unable to send message to to queue
at io.mosip.e2e.tests.EndToEndRun.uinGeneration(EndToEndRun.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:28)
]]>
    </error>
  </testcase> <!-- E2ERun_PrIdOfChildWithoutDocs_uinGeneration -->
</testsuite> <!-- io.mosip.e2e.tests.EndToEndRun -->
